# Generated by Codex on 2026-06-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("hr", "0005_planningshift_pointage_shift_tacheequipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="date_archivage",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="archive_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_archives",
                to="accounts.utilisateurprofile",
            ),
        ),
    ]
