# Generated by Codex on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_document_archive_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="planningshift",
            name="pause_debut",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
