# Generated by Django 5.0.6 on 2026-06-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_planningshift_pause_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerh',
            name='nom_piece_jointe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='messagerh',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='uploads/messages_rh/'),
        ),
        migrations.AlterField(
            model_name='messagerh',
            name='contenu',
            field=models.TextField(blank=True),
        ),
    ]
