# Generated by Django 5.0.6 on 2026-06-29 20:48

import django.db.models.deletion
from django.db import migrations, models


def backfill_leave_approvals(apps, schema_editor):
    DemandeConge = apps.get_model("hr", "DemandeConge")
    for demande in DemandeConge.objects.select_related("employe", "traitee_par"):
        updates = []
        if demande.statut == "VALIDEE":
            demande.manager_approval_status = "approved"
            demande.hr_approval_status = "approved"
            demande.manager_approved_by_id = demande.employe.responsable_id or demande.traitee_par_id
            demande.hr_approved_by_id = demande.traitee_par_id
            demande.manager_approved_at = demande.date_traitement
            demande.hr_approved_at = demande.date_traitement
            updates = [
                "manager_approval_status",
                "hr_approval_status",
                "manager_approved_by",
                "hr_approved_by",
                "manager_approved_at",
                "hr_approved_at",
            ]
        elif demande.statut == "REFUSEE":
            is_manager = demande.traitee_par_id and demande.employe.responsable_id == demande.traitee_par_id
            if is_manager:
                demande.manager_approval_status = "refused"
                demande.manager_approved_by_id = demande.traitee_par_id
                demande.manager_approved_at = demande.date_traitement
                demande.manager_refusal_reason = demande.commentaire_reponse or ""
                updates = ["manager_approval_status", "manager_approved_by", "manager_approved_at", "manager_refusal_reason"]
            else:
                demande.hr_approval_status = "refused"
                demande.hr_approved_by_id = demande.traitee_par_id
                demande.hr_approved_at = demande.date_traitement
                demande.hr_refusal_reason = demande.commentaire_reponse or ""
                updates = ["hr_approval_status", "hr_approved_by", "hr_approved_at", "hr_refusal_reason"]
        if updates:
            demande.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_messagerh_nom_piece_jointe_messagerh_piece_jointe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='hr_approval_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('refused', 'Refuse')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='hr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='hr_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves_rh', to='hr.employe'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='hr_refusal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='manager_approval_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('refused', 'Refuse')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves_manager', to='hr.employe'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='manager_refusal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(backfill_leave_approvals, migrations.RunPython.noop),
    ]
