# Generated by Django 5.0.6 on 2026-06-29 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hr', '0009_demandeconge_hr_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacheequipe',
            name='accepte_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_acceptees', to='hr.employe'),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='auto_assign_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='feedback_manager',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_manager', to='hr.employe'),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='max_acceptations',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='message_completion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='mode_affectation',
            field=models.CharField(choices=[('direct', 'Un employe'), ('team', "Toute l'equipe"), ('open', 'Tache ouverte')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='points_attribues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='points_attribues_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='points_attribues_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_taches_attribues', to='accounts.utilisateurprofile'),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='points_suggeres',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='taille',
            field=models.CharField(choices=[('petite', 'Petite'), ('moyenne', 'Moyenne'), ('grande', 'Grande')], default='moyenne', max_length=20),
        ),
        migrations.AlterField(
            model_name='tacheequipe',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('a_faire', 'Assignee'), ('ouverte', 'Ouverte'), ('acceptee', 'Acceptee'), ('en_cours', 'En cours'), ('soumise', "En attente d'approbation"), ('terminee', 'Terminee'), ('changements', 'Changements demandes'), ('rejetee', 'Rejetee'), ('annulee', 'Annulee'), ('archivee', 'Archivee')], default='a_faire', max_length=30),
        ),
        migrations.AlterField(
            model_name='transactionpoints',
            name='source',
            field=models.CharField(choices=[('pointage', 'Pointage'), ('boutique', 'Boutique'), ('conge', 'Conge'), ('formation', 'Formation'), ('manuel', 'Manuel'), ('reclamation', 'Reclamation'), ('tache', 'Tache')], max_length=30),
        ),
    ]
