# Generated by Django 5.0.6 on 2026-06-29 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_tacheequipe_accepte_par_tacheequipe_auto_assign_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacheequipe',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='hr.service'),
        ),
    ]
