# Generated by Django 5.0.6 on 2026-06-30 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hr', '0011_tacheequipe_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationrh',
            name='categorie',
            field=models.CharField(choices=[('general', 'Question generale'), ('administratif', 'Administratif'), ('paie', 'Paie'), ('conge', 'Conges et absences'), ('documents', 'Documents RH'), ('autre', 'Autre')], default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='conversationrh',
            name='cloture_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_rh_clotures', to='accounts.utilisateurprofile'),
        ),
        migrations.AddField(
            model_name='conversationrh',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationrh',
            name='detail_cloture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversationrh',
            name='motif_cloture',
            field=models.CharField(blank=True, choices=[('resolved', 'Issue resolved'), ('handled', 'Request handled'), ('duplicate', 'Duplicate request'), ('insufficient_info', 'Not enough information provided'), ('not_hr', 'Not HR-related'), ('invalid', 'Invalid or non-actionable request'), ('no_response', 'Closed after no response'), ('other', 'Other')], max_length=40),
        ),
        migrations.AddField(
            model_name='conversationrh',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationrh',
            name='statut',
            field=models.CharField(choices=[('ouverte', 'En cours'), ('en_attente', 'En attente RH'), ('attente_employe', 'En attente employe'), ('cloturee', 'Cloturee')], default='ouverte', max_length=30),
        ),
    ]
