# Generated by Django 5.0.6 on 2026-06-30 00:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hr', '0012_conversationrh_categorie_conversationrh_cloture_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationrh',
            name='date_note',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationrh',
            name='note_commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversationrh',
            name='note_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_rh_notes', to='hr.employe'),
        ),
        migrations.AddField(
            model_name='conversationrh',
            name='note_support',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationrh',
            name='numero_ticket',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conversationrh',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tickets_rh_participation', to='hr.employe'),
        ),
        migrations.CreateModel(
            name='SupportRHReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('total_etoiles', models.PositiveIntegerField(default=0)),
                ('rang', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('pending', 'Pending manager approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('awarded', 'Points awarded')], default='pending', max_length=20)),
                ('date_generation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recompenses_support_approuvees', to='accounts.utilisateurprofile')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompenses_support_rh', to='hr.employe')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recompenses_support_generees', to='accounts.utilisateurprofile')),
            ],
            options={
                'ordering': ['mois', 'rang', '-total_etoiles'],
            },
        ),
        migrations.AddConstraint(
            model_name='supportrhreward',
            constraint=models.UniqueConstraint(fields=('employe', 'mois'), name='unique_support_reward_employee_month'),
        ),
    ]
