# Generated by Django 5.0.6 on 2026-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_planningshift_permanent_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningshift',
            name='recurrence_rule',
            field=models.CharField(choices=[('none', 'Aucune'), ('weekdays', 'Jours ouvrables'), ('daily', 'Tous les jours'), ('weekly', 'Hebdomadaire'), ('biweekly', 'Toutes les deux semaines'), ('monthly', 'Mensuelle')], default='none', max_length=20),
        ),
    ]
