# Generated by Django 5.0.6 on 2026-07-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_alter_planningshift_recurrence_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldeconge',
            name='jours_disponibles',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6),
        ),
    ]
