# Generated by Django 5.0.6 on 2026-07-01 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountcreationrequest_email_verified_and_more'),
        ('hr', '0016_alter_soldeconge_jours_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacheequipe',
            name='nom_piece_jointe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='obligatoire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tacheequipe',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='uploads/taches/'),
        ),
        migrations.CreateModel(
            name='TacheEquipeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='uploads/taches/messages/')),
                ('nom_piece_jointe', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_taches', to='accounts.utilisateurprofile')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hr.tacheequipe')),
            ],
            options={
                'ordering': ['date_creation', 'id'],
            },
        ),
    ]
