# Generated by Django 5.0.6 on 2026-07-01 05:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_tacheequipe_nom_piece_jointe_tacheequipe_obligatoire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustementpointsmanuel',
            name='ticket_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustements_points', to='hr.conversationrh'),
        ),
        migrations.AlterField(
            model_name='transactionpoints',
            name='source',
            field=models.CharField(choices=[('pointage', 'Pointage'), ('boutique', 'Boutique'), ('conge', 'Conge'), ('formation', 'Formation'), ('manuel', 'Manuel'), ('ticket', 'Ticket support'), ('reclamation', 'Reclamation'), ('tache', 'Tache')], max_length=30),
        ),
        migrations.CreateModel(
            name='ActualitePieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='uploads/actualites/pieces/')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='hr.actualite')),
            ],
            options={
                'ordering': ['nom_fichier'],
            },
        ),
    ]
