# Generated by Django 5.0.6 on 2026-07-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_ajustementpointsmanuel_ticket_lie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationrh',
            name='motif_cloture',
            field=models.CharField(blank=True, choices=[('resolved', 'Probleme resolu'), ('handled', 'Demande traitee'), ('duplicate', 'Demande en double'), ('insufficient_info', 'Informations insuffisantes'), ('not_hr', 'Hors perimetre RH'), ('invalid', 'Demande invalide ou non exploitable'), ('no_response', 'Cloture sans reponse'), ('other', 'Autre')], max_length=40),
        ),
    ]
